configure.in:  * --enable-lwres is substituted by more generic --with-backend which may take    values "resolv" (default) and "lwres".  * Presence and usability of essential lwres headers and library is checked.
configure: Regen.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1297,7 +1297,6 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --enable-lwres          use lwres for DNS resolution (default: no)
   --enable-threads        build with threads
   --enable-shared         build and link with shared libraries (default: on)
   --enable-64bit          enable 64bit support (default: off)
@@ -1313,6 +1312,8 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-tcl              directory containing tcl configuration
                           (tclConfig.sh)
+  --with-backend          backend to use for DNS resolution (resolv (default),
+                          lwres)
   --with-tclinclude       directory containing the public Tcl header files
   --with-celib=DIR        use Windows/CE support library from DIR
 
@@ -6693,38 +6694,8 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
     CLEANFILES="$CLEANFILES *.lib *.dll *.exp *.ilk *.pdb vc*.pch"
-    #TEA_ADD_SOURCES([win/winFile.c])
-    #TEA_ADD_INCLUDES([-I\"$(${CYGPATH} ${srcdir}/win)\"])
-else
-	:
-fi
 
-
-#--------------------------------------------------------------------
-# Selection of the facility for performing DNS RR resolution requests.
-# resolver and lwres are supported, resolver is the default.
-#--------------------------------------------------------------------
-if test "${TEA_PLATFORM}" = "unix" ; then
-	{ echo "$as_me:$LINENO: checking what facility to use for DNS RR resolution" >&5
-echo $ECHO_N "checking what facility to use for DNS RR resolution... $ECHO_C" >&6; }
-	# Check whether --enable-lwres was given.
-if test "${enable_lwres+set}" = set; then
-  enableval=$enable_lwres; use_lwres=$enableval
-else
-  use_lwres=no
-fi
-
-
-	if test "$use_lwres+set" = "set"; then
-		use_lwres=no
-	fi
-
-	if test "$use_lwres" = "yes" ; then
-		{ echo "$as_me:$LINENO: result: lwres" >&5
-echo "${ECHO_T}lwres" >&6; }
-		#AC_DEFINE(USE_LWRES, 1, [Use lwres for DNS resolution])
-
-    vars="unix/lwres.c"
+    vars="win/windns.c"
     for i in $vars; do
 	case $i in
 	    \$*)
@@ -6759,21 +6730,33 @@ echo "$as_me: error: could not find source file '$i'" >&2;}
 
 
 
-
-    vars="-llwres"
-    for i in $vars; do
-	if test "${TEA_PLATFORM}" = "windows" -a "$GCC" = "yes" ; then
-	    # Convert foo.lib to -lfoo for GCC.  No-op if not *.lib
-	    i=`echo "$i" | sed -e 's/^\([^-].*\)\.lib$/-l\1/i'`
-	fi
-	PKG_LIBS="$PKG_LIBS $i"
-    done
+    #TEA_ADD_INCLUDES([-I\"$(${CYGPATH} ${srcdir}/win)\"])
+else
+	:
+fi
 
 
-	else
-		{ echo "$as_me:$LINENO: result: resolv" >&5
+#--------------------------------------------------------------------
+# Selection of the backend for performing DNS resolution requests.
+# resolv and lwres are supported, resolv is the default.
+#--------------------------------------------------------------------
+if test "${TEA_PLATFORM}" = "unix" ; then
+	{ echo "$as_me:$LINENO: checking what backend to use for DNS resolution" >&5
+echo $ECHO_N "checking what backend to use for DNS resolution... $ECHO_C" >&6; }
+
+# Check whether --with-backend was given.
+if test "${with_backend+set}" = set; then
+  withval=$with_backend; backend=${withval}
+else
+  backend=resolv
+fi
+
+
+	case $backend in
+		resolv)
+			{ echo "$as_me:$LINENO: result: resolv" >&5
 echo "${ECHO_T}resolv" >&6; }
-		cat >>confdefs.h <<\_ACEOF
+			cat >>confdefs.h <<\_ACEOF
 #define USE_LWRES 0
 _ACEOF
 
@@ -6824,7 +6807,272 @@ echo "$as_me: error: could not find source file '$i'" >&2;}
     done
 
 
+		;;
+		lwres)
+			{ echo "$as_me:$LINENO: result: lwres" >&5
+echo "${ECHO_T}lwres" >&6; }
+			if test "${ac_cv_header_lwres_netdb_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for lwres/netdb.h" >&5
+echo $ECHO_N "checking for lwres/netdb.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_lwres_netdb_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_lwres_netdb_h" >&5
+echo "${ECHO_T}$ac_cv_header_lwres_netdb_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking lwres/netdb.h usability" >&5
+echo $ECHO_N "checking lwres/netdb.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <lwres/netdb.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking lwres/netdb.h presence" >&5
+echo $ECHO_N "checking lwres/netdb.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <lwres/netdb.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: lwres/netdb.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: lwres/netdb.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: lwres/netdb.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: lwres/netdb.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: lwres/netdb.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: lwres/netdb.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: lwres/netdb.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: lwres/netdb.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: lwres/netdb.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: lwres/netdb.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: lwres/netdb.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: lwres/netdb.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: lwres/netdb.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: lwres/netdb.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: lwres/netdb.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: lwres/netdb.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for lwres/netdb.h" >&5
+echo $ECHO_N "checking for lwres/netdb.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_lwres_netdb_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_lwres_netdb_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_lwres_netdb_h" >&5
+echo "${ECHO_T}$ac_cv_header_lwres_netdb_h" >&6; }
+
+fi
+if test $ac_cv_header_lwres_netdb_h = yes; then
+  :
+else
+  { echo "$as_me:$LINENO: WARNING: Probably lwres library header files are missing" >&5
+echo "$as_me: WARNING: Probably lwres library header files are missing" >&2;}
+fi
+
+
+
+{ echo "$as_me:$LINENO: checking for lwres_getrrsetbyname in -llwres" >&5
+echo $ECHO_N "checking for lwres_getrrsetbyname in -llwres... $ECHO_C" >&6; }
+if test "${ac_cv_lib_lwres_lwres_getrrsetbyname+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llwres  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char lwres_getrrsetbyname ();
+int
+main ()
+{
+return lwres_getrrsetbyname ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_lwres_lwres_getrrsetbyname=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_lwres_lwres_getrrsetbyname=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_lwres_lwres_getrrsetbyname" >&5
+echo "${ECHO_T}$ac_cv_lib_lwres_lwres_getrrsetbyname" >&6; }
+if test $ac_cv_lib_lwres_lwres_getrrsetbyname = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBLWRES 1
+_ACEOF
+
+  LIBS="-llwres $LIBS"
+
+else
+  { echo "$as_me:$LINENO: WARNING: Probably lwres library is not available" >&5
+echo "$as_me: WARNING: Probably lwres library is not available" >&2;}
+fi
+
+			#AC_DEFINE(USE_LWRES, 1, [Use lwres for DNS resolution])
+
+    vars="unix/lwres.c"
+    for i in $vars; do
+	case $i in
+	    \$*)
+		# allow $-var names
+		PKG_SOURCES="$PKG_SOURCES $i"
+		PKG_OBJECTS="$PKG_OBJECTS $i"
+		;;
+	    *)
+		# check for existence - allows for generic/win/unix VPATH
+		# To add more dirs here (like 'src'), you have to update VPATH
+		# in Makefile.in as well
+		if test ! -f "${srcdir}/$i" -a ! -f "${srcdir}/generic/$i" \
+		    -a ! -f "${srcdir}/win/$i" -a ! -f "${srcdir}/unix/$i" \
+		    ; then
+		    { { echo "$as_me:$LINENO: error: could not find source file '$i'" >&5
+echo "$as_me: error: could not find source file '$i'" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+		PKG_SOURCES="$PKG_SOURCES $i"
+		# this assumes it is in a VPATH dir
+		i=`basename $i`
+		# handle user calling this before or after TEA_SETUP_COMPILER
+		if test x"${OBJEXT}" != x ; then
+		    j="`echo $i | sed -e 's/\.[^.]*$//'`.${OBJEXT}"
+		else
+		    j="`echo $i | sed -e 's/\.[^.]*$//'`.\${OBJEXT}"
+		fi
+		PKG_OBJECTS="$PKG_OBJECTS $j"
+		;;
+	esac
+    done
+
+
+
+
+    vars="-llwres"
+    for i in $vars; do
+	if test "${TEA_PLATFORM}" = "windows" -a "$GCC" = "yes" ; then
+	    # Convert foo.lib to -lfoo for GCC.  No-op if not *.lib
+	    i=`echo "$i" | sed -e 's/^\([^-].*\)\.lib$/-l\1/i'`
 	fi
+	PKG_LIBS="$PKG_LIBS $i"
+    done
+
+
+		;;
+		*)
+			{ { echo "$as_me:$LINENO: error: Invalid DNS resolution backend: $with_backend" >&5
+echo "$as_me: error: Invalid DNS resolution backend: $with_backend" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+	esac
 fi
 
 #--------------------------------------------------------------------
